annotations:
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/piraeus-charts/snapshot-controller
apiVersion: v2
appVersion: v6.2.2
description: |
  Deploys the snapshot-validation-webhook and configures your cluster to validate every `VolumeSnapshot` and
  `VolumeSnapshotContent` resource by sending it to the webhook.
home: https://github.com/piraeusdatastore/helm-charts
icon: https://raw.githubusercontent.com/piraeusdatastore/piraeus/master/artwork/sandbox-artwork/icon/color.svg
keywords:
- storage
- snapshot
- validation
maintainers:
- name: The Piraeus Maintainers
  url: https://github.com/piraeusdatastore/
name: rke2-snapshot-validation-webhook
sources:
- https://github.com/kubernetes-csi/external-snapshotter/
type: application
version: 1.7.302
