annotations:
  artifacthub.io/changes: |
    - "[8890](https://github.com/kubernetes/ingress-nginx/pull/8890) migrate to endpointslices"
    - "[9059](https://github.com/kubernetes/ingress-nginx/pull/9059) kubewebhookcertgen sha change after go1191"
    - "[9046](https://github.com/kubernetes/ingress-nginx/pull/9046) Parameterize metrics port name"
    - "[9104](https://github.com/kubernetes/ingress-nginx/pull/9104) Fix yaml formatting error with multiple annotations"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: 1.4.0
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and
  load balancer
home: https://github.com/kubernetes/ingress-nginx
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
- ingress
- nginx
kubeVersion: '>=1.20.0-0'
maintainers:
- name: rikatz
- name: strongjz
- name: tao12345666333
name: rke2-ingress-nginx
sources:
- https://github.com/kubernetes/ingress-nginx
version: 4.3.001
