{{ if .Values.installation.enabled }}
{{ $installSpec := omit .Values.installation "enabled" }}
{{ $installSpec := omit $installSpec "backend" }}
{{ $installSpec := omit $installSpec "natOutgoing" }}
{{ $_ := set $installSpec "imagePullSecrets" (include "tigera-operator.imagePullSecrets" . | fromYamlArray) }}
{{ $defaultRegistry := get $installSpec "registry" }}
{{ $finalRegistry := coalesce .Values.global.systemDefaultRegistry $defaultRegistry }}
{{ $_ := set $installSpec "registry" $finalRegistry }}
{{ if empty .Values.installation.calicoNetwork.ipPools }}
{{ $calicoNetwork := get .Values.installation "calicoNetwork" }}
{{ if not (empty .Values.global.clusterCIDRv4) }}
{{ $myIP4Dict := dict "natOutgoing" .Values.installation.natOutgoing "encapsulation" .Values.installation.backend "cidr" .Values.global.clusterCIDRv4 }}
{{ if not (empty .Values.global.clusterCIDRv6) }}
{{ $myIP6Dict := dict "natOutgoing" .Values.installation.natOutgoing "encapsulation" .Values.installation.backend "cidr" .Values.global.clusterCIDRv6 }}
{{ $ipPoolList := list $myIP4Dict }}
{{ $finalIpPoolList := append $ipPoolList $myIP6Dict }}
{{ $_ := set $calicoNetwork "ipPools" $finalIpPoolList }}
{{ else }}
{{ $finalIpPoolList := list $myIP4Dict }}
{{ $_ := set $calicoNetwork "ipPools" $finalIpPoolList }}
{{ end }}
{{ else if not (empty .Values.global.clusterCIDRv6) }}
{{ $myIP6Dict := dict "natOutgoing" .Values.installation.natOutgoing "encapsulation" .Values.installation.backend "cidr" .Values.global.clusterCIDRv6 }}
{{ $finalIpPoolList := list $myIP6Dict }}
{{ $_ := set $calicoNetwork "ipPools" $finalIpPoolList }}
{{ end }}
{{ if empty .Values.installation.calicoNetwork.nodeAddressAutodetectionV4 }}
{{ if not (empty .Values.global.clusterCIDRv4) }}
{{ $calicoNetwork := get .Values.installation "calicoNetwork" }}
{{ $autodetect := dict "firstFound" true }}
{{ $_ := set $calicoNetwork "nodeAddressAutodetectionV4" $autodetect }}
{{ end }}
{{ end }}
{{ if empty .Values.installation.calicoNetwork.nodeAddressAutodetectionV6 }}
{{ if not (empty .Values.global.clusterCIDRv6) }}
{{ $calicoNetwork := get .Values.installation "calicoNetwork" }}
{{ $autodetect := dict "firstFound" true }}
{{ $_ := set $calicoNetwork "nodeAddressAutodetectionV6" $autodetect }}
{{ end }}
{{ end }}
{{ end }}

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
{{ $installSpec | toYaml | indent 2 }}

{{ end }}

{{ if .Values.apiServer.enabled }}
{{ $apiServerSpec := omit .Values.apiServer "enabled" }}
---

apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec:
{{ $apiServerSpec | toYaml | indent 2 }}
{{ end }}

{{ if .Values.goldmane.enabled }}
{{ $goldmaneSpec := omit .Values.goldmane "enabled" }}
---

apiVersion: operator.tigera.io/v1
kind: Goldmane
metadata:
  name: default
spec:
{{ $goldmaneSpec | toYaml | indent 2 }}
{{ end }}

{{ if .Values.whisker.enabled }}
{{ $whiskerSpec := omit .Values.whisker "enabled" }}
---

apiVersion: operator.tigera.io/v1
kind: Whisker
metadata:
  name: default
spec:
{{ $whiskerSpec | toYaml | indent 2 }}
{{ end }}
