apiVersion: v1
appVersion: v1.0.0
description: Install SR-IOV operator, cni and device polugin.
home: https://github.com/k8snetworkplumbingwg/sriov-network-operator
keywords:
- sr-iov
maintainers:
- email: charts@rancher.com
  name: Rancher Labs
name: rke2-sriov
sources:
- https://github.com/rancher/rke2-charts
version: v1.0.0-build2021042901
