# imagePullSecrets is a special helm field which, when specified, creates a secret
# containing the pull secret which is used to pull all images deployed by this helm chart and the resulting operator.
# this field is a map where the key is the desired secret name and the value is the contents of the imagePullSecret.
#
# Example: --set-file imagePullSecrets.gcr=./pull-secret.json
imagePullSecrets: {}

installation:
  controlPlaneTolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/etcd"
    operator: "Exists"
    effect: "NoExecute"
  enabled: true
  kubeletVolumePluginPath: "None"
  kubernetesProvider: ""
  calicoNetwork:
    bgp: Disabled
  imagePath: "rancher"
  imagePrefix: "mirrored-calico-"
  flexVolumePath: "/var/lib/kubelet/volumeplugins/"
  # imagePullSecrets are configured on all images deployed by the tigera-operator.
  # secrets specified here must exist in the tigera-operator namespace; they won't be created by the operator or helm.
  # imagePullSecrets are a slice of LocalObjectReferences, which is the same format they appear as on deployments.
  #
  # Example: --set installation.imagePullSecrets[0].name=my-existing-secret
  imagePullSecrets: []

apiServer:
  enabled: false

certs:
  node:
    key:
    cert:
    commonName:
  typha:
    key:
    cert:
    commonName:
    caBundle:

# Resource requests and limits for the tigera/operator pod.
resources: {}

# Tolerations for the tigera/operator pod.
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists

# NodeSelector for the tigera/operator pod.
nodeSelector:
  kubernetes.io/os: linux

# Custom annotations for the tigera/operator pod.
podAnnotations: {}

# Custom labels for the tigera/operator pod.
podLabels: {}

# Image and registry configuration for the tigera/operator pod.
tigeraOperator:
  image: rancher/mirrored-calico-operator
  version: v1.32.3
  registry: docker.io
calicoctl:
  image: rancher/mirrored-calico-ctl
  tag: v3.27.0

global:
  systemDefaultRegistry: ""
  clusterCIDRv4: ""
  clusterCIDRv6: ""

# Config required by Windows nodes
ipamConfig:
  strictAffinity: true
  autoAllocateBlocks: true

felixConfiguration:
  wireguardEnabled: false
  # Config required to fix RKE2 issue #1541
  featureDetectOverride: "ChecksumOffloadBroken=true"
  healthPort: 9099
  defaultEndpointToHostAction: "Drop"
  logSeveritySys: "Info"
  xdpEnabled: true
