#{{- if gt (len (lookup "rbac.authorization.k8s.io/v1" "ClusterRole" "" "")) 0 -}}
# {{- $found := dict -}}
# {{- set $found "gateway.networking.k8s.io/v1/GatewayClass" false -}}
# {{- set $found "gateway.networking.k8s.io/v1/Gateway" false -}}
# {{- set $found "gateway.networking.k8s.io/v1/GRPCRoute" false -}}
# {{- set $found "gateway.networking.k8s.io/v1/HTTPRoute" false -}}
# {{- set $found "gateway.networking.k8s.io/v1beta1/ReferenceGrant" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/AccessControlPolicy" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/AIService" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIAuth" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIBundle" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APICatalogItem" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIPlan" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIPortalAuth" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIPortal" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIRateLimit" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/API" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/APIVersion" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/ManagedApplication" false -}}
# {{- set $found "hub.traefik.io/v1alpha1/ManagedSubscription" false -}}
# {{- set $found "traefik.io/v1alpha1/IngressRoute" false -}}
# {{- set $found "traefik.io/v1alpha1/IngressRouteTCP" false -}}
# {{- set $found "traefik.io/v1alpha1/IngressRouteUDP" false -}}
# {{- set $found "traefik.io/v1alpha1/Middleware" false -}}
# {{- set $found "traefik.io/v1alpha1/MiddlewareTCP" false -}}
# {{- set $found "traefik.io/v1alpha1/ServersTransport" false -}}
# {{- set $found "traefik.io/v1alpha1/ServersTransportTCP" false -}}
# {{- set $found "traefik.io/v1alpha1/TLSOption" false -}}
# {{- set $found "traefik.io/v1alpha1/TLSStore" false -}}
# {{- set $found "traefik.io/v1alpha1/TraefikService" false -}}
# {{- range .Capabilities.APIVersions -}}
# {{- if hasKey $found (toString .) -}}
# 	{{- set $found (toString .) true -}}
# {{- end -}}
# {{- end -}}
# {{- range $_, $exists := $found -}}
# {{- if (eq $exists false) -}}
# 	{{- required "Required CRDs are missing. Please install the corresponding CRD chart before installing this chart." "" -}}
# {{- end -}}
# {{- end -}}
#{{- end -}}