annotations:
  fleet.cattle.io/bundle-id: rke2
apiVersion: v2
appVersion: v2.11.10
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.16.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: rke2-traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 27.0.200
