apiVersion: v1
name: rke2-cilium
description: eBPF-based Networking, Security, and Observability
version: 1.9.8
kubeVersion: '>= 1.12.0-0'
home: https://cilium.io/
keywords:
  - cilium
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
