apiVersion: v1
name: rke2-canal
description: Install Canal Network Plugin.
version: v3.29.7-build20251120
appVersion: v3.29.7
home: https://www.projectcalico.org/
keywords:
  - canal
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
