{{- if .Values.providers.kubernetesIngressNginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: rke2-ingress-nginx-migration
spec:
  controller: rke2.cattle.io/ingress-nginx-migration
{{- end -}}
