apiVersion: v1
name: rke2-kube-proxy
description: Install Kube Proxy.
version: v1.21.12-rke2r2-build20220428
appVersion: v1.21.12-rke2r2
keywords:
  - kube-proxy
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
