apiVersion: v1
name: rke2-kube-proxy
description: Install Kube Proxy.
version: v1.19.10-build20210419
appVersion: v1.19.10
keywords:
  - kube-proxy
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
