apiVersion: v1
name: rke2-kube-proxy
description: Install Kube Proxy.
version: v1.20.5-build20210318
appVersion: v1.20.5
keywords:
  - kube-proxy
sources:
  - https://github.com/rancher/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
