{{- if and .Values.deployment.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "coredns.clusterRoleName" . }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
{{- with .Values.customAnnotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "coredns.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "coredns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
