apiVersion: v1
name: rke2-multus
description: Multus CNI enables attaching multiple network interfaces to pods in Kubernetes.
version: v3.7.1-build20210416
appVersion: v3.7.1
home: https://github.com/k8snetworkplumbingwg/multus-cni
icon: https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/doc/images/Multus.png
sources:
  - https://github.com/k8snetworkplumbingwg/multus-cni
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
