url: https://traefik.github.io/charts/traefik/traefik-27.0.2.tgz
packageVersion: 02
# This repository does not use releaseCandidateVersions, so you can leave this as 00.
releaseCandidateVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
